### ISSUE TITLE
Wierd Error message when any keybind pressed

### ISSUE THREAD

**Issue by Stavro-Purdie** [Stavro-Purdie/Universal-Digital-Visual-Follow-Spot-Interfacing-System#2]
Wierd error message when any keybind pressed. 

`[[AUnhandled exception in listener callback
Traceback (most recent call last):
  File "/home/spurdie/.local/lib/python3.10/site-packages/pynput/_util/__init__.py", line 229, in inner
    return f(self, *args, **kwargs)
  File "/home/spurdie/.local/lib/python3.10/site-packages/pynput/_util/xorg.py", line 470, in _handler
    self._handle(self._display_stop, event)
  File "/home/spurdie/.local/lib/python3.10/site-packages/pynput/keyboard/_xorg.py", line 578, in _handle
    self.on_press(key)
  File "/home/spurdie/.local/lib/python3.10/site-packages/pynput/_util/__init__.py", line 145, in inner
    if f(*args) is False:
  File "/home/spurdie/Desktop/Scholarship/Universal-Digital-Visual-Follow-Spot-Interfacing-System/dmx_control_V0.1_ALPHA.py", line 234, in on_press
    red += 1
UnboundLocalError: local variable 'red' referenced before assignment
Traceback (most recent call last):
  File "/home/spurdie/Desktop/Scholarship/Universal-Digital-Visual-Follow-Spot-Interfacing-System/dmx_control_V0.1_ALPHA.py", line 617, in <module>
    dmxcontrol()
  File "/home/spurdie/Desktop/Scholarship/Universal-Digital-Visual-Follow-Spot-Interfacing-System/dmx_control_V0.1_ALPHA.py", line 557, in dmxcontrol
    listener.join()
  File "/home/spurdie/.local/lib/python3.10/site-packages/pynput/_util/__init__.py", line 281, in join
    six.reraise(exc_type, exc_value, exc_traceback)
  File "/usr/lib/python3/dist-packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "/home/spurdie/.local/lib/python3.10/site-packages/pynput/_util/__init__.py", line 229, in inner
    return f(self, *args, **kwargs)
  File "/home/spurdie/.local/lib/python3.10/site-packages/pynput/_util/xorg.py", line 470, in _handler
    self._handle(self._display_stop, event)
  File "/home/spurdie/.local/lib/python3.10/site-packages/pynput/keyboard/_xorg.py", line 578, in _handle
    self.on_press(key)
  File "/home/spurdie/.local/lib/python3.10/site-packages/pynput/_util/__init__.py", line 145, in inner
    if f(*args) is False:
  File "/home/spurdie/Desktop/Scholarship/Universal-Digital-Visual-Follow-Spot-Interfacing-System/dmx_control_V0.1_ALPHA.py", line 234, in on_press
    red += 1
UnboundLocalError: local variable 'red' referenced before assignment`

**Comment by Stavro-Purdie** [comment]
It appears to be an issue with the if isrgb == True statements outside of the colour  loop. I will put them inside each colour loop but I may need to just combine it into one big whole loop for a permanent fix.

**Comment by Stavro-Purdie** [comment]
After further testing I can confirm that this is not the issue. Instead it appears that the main issue is the variables not being initialized. I may need to move the global statements to the top of the program as per [https://stackoverflow.com/questions/10851906/python-3-unboundlocalerror-local-variable-referenced-before-assignment](url) this article

**Comment by Stavro-Purdie** [comment]
This error has been fixed by moving all the global statements for the fixtures to the `on_press` function.
